-- VHDL module instantiation generated by SCUBA Diamond_3.1_Production (93)
-- Module  Version: 6.3
-- Wed Sep 24 23:28:04 2014

-- parameterized module component declaration
component ram_dp
    port (WrAddress: in  std_logic_vector(11 downto 0); 
        RdAddress: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(31 downto 0); WE: in  std_logic; 
        RdClock: in  std_logic; RdClockEn: in  std_logic; 
        Reset: in  std_logic; WrClock: in  std_logic; 
        WrClockEn: in  std_logic; Q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : ram_dp
    port map (WrAddress(11 downto 0)=>__, RdAddress(11 downto 0)=>__, 
        Data(31 downto 0)=>__, WE=>__, RdClock=>__, RdClockEn=>__, Reset=>__, 
        WrClock=>__, WrClockEn=>__, Q(31 downto 0)=>__);
