-- VHDL module instantiation generated by SCUBA Diamond_3.1_Production (93)
-- Module  Version: 7.3
-- Thu Sep 25 00:06:19 2014

-- parameterized module component declaration
component ram_dq
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(31 downto 0); 
        Q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : ram_dq
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(11 downto 0)=>__, 
        Data(31 downto 0)=>__, Q(31 downto 0)=>__);
